<?xml version="1.0" encoding="utf-8"?><Database Name="Monti" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-6B31F1H\SQLEXPRESS;Initial Catalog=Monti;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MontiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Genre" Member="Genre">
    <Type Name="Genre">
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movie" Member="Movie">
    <Type Name="Movie">
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Director" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Genre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Runtime" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetGenre1" Method="GetGenre1">
    <Parameter Name="id" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="GetGenre1Result">
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>