using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Xml;

namespace DDAPractica9
{
    public partial class _Default : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }
        protected void cmdCreateXml_Click1(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"d:\EjercicioPropuesto.xml", FileMode.Create);
            XmlTextWriter w = new XmlTextWriter(fs, null);

            w.WriteStartDocument();
            w.WriteStartElement("EjercicioPropuesto");
            w.WriteComment("This file generated by the XmlTextWriter class.");

            w.WriteStartElement("Trabajador");
            w.WriteAttributeString("Codigo", "", "123");
            w.WriteAttributeString("Nombre", "", "Diego");
            w.WriteAttributeString("Area", "", "Turismo");
            w.WriteAttributeString("Sueldo", "", "4300");
            w.WriteEndElement();

            w.WriteStartElement("Trabajador");
            w.WriteAttributeString("Codigo", "", "247");
            w.WriteAttributeString("Nombre", "", "Joshua");
            w.WriteAttributeString("Area", "", "Administracion");
            w.WriteAttributeString("Sueldo", "", "5100");
            w.WriteEndElement();

            w.WriteEndElement();
            w.WriteEndDocument();
            w.Close();
            lblXml.Text = @"File d:\EjercicioPropuesto.xml written successfully.";
        }

        protected void cmdReadXml_Click(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"d:\EjercicioPropuesto.xml", FileMode.Open);
            XmlTextReader r = new XmlTextReader(fs);

            StringWriter writer = new StringWriter();

            while (r.Read())
            {
                writer.Write("<b>Type:</b> ");
                writer.Write(r.NodeType.ToString());
                writer.Write("<br>");

                if (r.Name != "")
                {
                    writer.Write("<b>Name:</b> ");
                    writer.Write(r.Name);
                    writer.Write("<br>");
                }
                
                if (r.Value != "")
                {
                    writer.Write("<b>Value:</b> ");
                    writer.Write(r.Value);
                    writer.Write("<br>");
                }
                
                if (r.AttributeCount > 0)
                {
                    writer.Write("<b>Attributes:</b> ");
                    for (int i = 0; i < r.AttributeCount; i++)
                    {
                        writer.Write("  ");
                        writer.Write(r.GetAttribute(i));
                        writer.Write("  ");
                    }
                    writer.Write("<br>");
                }
                writer.Write("<br>");
            }
            r.Close();
            lblXml.Text = writer.ToString();
        }

        protected void cdmReadXmlAsObjects_Click(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"d:\EjercicioPropuesto.xml", FileMode.Open);
            XmlTextReader r = new XmlTextReader(fs);

            List<Class1> trabajadores = new List<Class1>();
            
            while (r.Read())
            {
                if (r.NodeType == XmlNodeType.Element && r.Name == "Class1")
                {
                    Class1 Trabajador1 = new Class1();
                    Trabajador1.Codigo = Int32.Parse(r.GetAttribute(0));
                    Trabajador1.Nombre = r.GetAttribute(1);
                    Trabajador1.Area = r.GetAttribute(2);
                    Trabajador1.Sueldo = Decimal.Parse(r.Value);
                    trabajadores.Add(Trabajador1);
                }
            }
            r.Close();
            gridResults.DataSource = trabajadores;
            gridResults.DataBind();
        }
    }
}